apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hazelcast-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - nodes
      - services
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hazelcast-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hazelcast-cluster-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-monitor-deployment
  labels:
    app: ws-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ws-monitor
  template:
    metadata:
      labels:
        app: ws-monitor
    spec:
      containers:
        - name: ws-monitor-container
          image: hataketed/ws-monitor:1.1.0
          ports:
            - containerPort: 8080
          env:
            - name: MONITOR_K8S_SERVICE
              value: ws-monitor-service
---
apiVersion: v1
kind: Service
metadata:
  name: ws-monitor-service
spec:
  type: NodePort
  selector:
    app: ws-monitor
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 8080