spring:
  application:
    name: WS-MONITOR
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        service-labels:
          spring-boot: true
  boot:
    admin:
      context-path: /monitor
monitor:
  k8s:
    service: ws-monitor-service